{eloquent} ros-distro.inc: add mapping for libboost-program-options
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-libboost-program-options' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/navigation2/nav2-util_0.3.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libboost-program-options' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-system-tests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-system-tests', 'nav2-lifecycle-manager', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-lifecycle-manager' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-lifecycle-manager', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup', 'navigation2', 'nav2-lifecycle-manager', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-bringup-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup-dev', 'navigation2', 'nav2-lifecycle-manager', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation2', 'nav2-lifecycle-manager', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'navigation2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation2-dev', 'nav2-lifecycle-manager', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-lifecycle-manager-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-lifecycle-manager-dev', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-recoveries' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-recoveries', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-recoveries-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-recoveries-dev', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-navfn-planner' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-navfn-planner', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-dwb-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-dwb-controller', 'dwb-plugins', 'dwb-core', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'dwb-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dwb-plugins', 'dwb-core', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'dwb-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dwb-plugins-dev', 'dwb-core', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'dwb-critics' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dwb-critics', 'dwb-core', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'dwb-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dwb-core', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-planner' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-planner', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nonpersistent-voxel-layer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nonpersistent-voxel-layer', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-controller', 'nav2-core', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-core', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'costmap-queue' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['costmap-queue', 'nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-costmap-2d' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-costmap-2d', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-costmap-2d-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-costmap-2d-dev', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-amcl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-amcl', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-amcl-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-amcl-dev', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav-2d-utils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav-2d-utils', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-map-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-map-server', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-bt-navigator' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bt-navigator', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-waypoint-follower' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-waypoint-follower', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-behavior-tree' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-behavior-tree', 'nav2-util', 'UNRESOLVED-libboost-program-options']
NOTE: Runtime target 'nav2-util' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-util', 'UNRESOLVED-libboost-program-options']
ERROR: Nothing RPROVIDES 'nav2-util-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/navigation2/nav2-util_0.3.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'nav2-util-dev'
NOTE: Runtime target 'nav2-util-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-util-dev']
ERROR: Nothing RPROVIDES 'nav2-navfn-planner-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/navigation2/nav2-navfn-planner_0.3.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'nav2-navfn-planner-dev'
NOTE: Runtime target 'nav2-navfn-planner-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-navfn-planner-dev']
ERROR: Nothing RPROVIDES 'dwb-core-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/navigation2/dwb-core_0.3.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dwb-core-dev'
NOTE: Runtime target 'dwb-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dwb-core-dev']
ERROR: Nothing RPROVIDES 'nav2-system-tests-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/navigation2/nav2-system-tests_0.3.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'nav2-system-tests-dev'
NOTE: Runtime target 'nav2-system-tests-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-system-tests-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>