{foxy} zstd-vendor: fix pkgconfig QA issue
* fixes prefix variable in libzstd.pc pointing to the prefix
  used by ExternalProject_Add instead of the path on target

  ERROR: zstd-vendor-0.2.7-1-r0 do_populate_sysroot: QA Issue:
  libzstd.pc failed sanity test (tmpdir) in path
  /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/zstd-vendor/0.2.7-1-r0/sysroot-destdir/usr/lib/pkgconfig
  [pkgconfig]

Signed-off-by: Martin Jansa <martin.jansa@lge.com>