{foxy} spdlog-vendor: resolve UNRESOLVED-spdlog
* this time we don't need to create
  spdlog_1.3.1.bb recipe, because 1.1.1-1 version if foxy actually
  explicitly asks for 1.5.0 which is in meta-oe, see:
  https://github.com/ros2-gbp/spdlog_vendor-release/compare/release/eloquent/spdlog_vendor/1.0.1-1...release/foxy/spdlog_vendor/1.1.1-1#diff-af3b638bc2a3e6c650974192a53c7291L74

* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-spdlog' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/spdlog-vendor/spdlog-vendor_1.1.1-1.bb, ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rcl-logging/rcl-logging-spdlog_0.4.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'spdlog-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['spdlog-vendor', 'UNRESOLVED-spdlog']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'spdlog-vendor', 'UNRESOLVED-spdlog']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'spdlog-vendor', 'UNRESOLVED-spdlog']
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'spdlog-vendor', 'UNRESOLVED-spdlog']
NOTE: Runtime target 'rcl-logging-spdlog' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rcl-logging-spdlog', 'spdlog-vendor', 'UNRESOLVED-spdlog']
ERROR: Nothing PROVIDES 'spdlog-vendor' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rcl-logging/rcl-logging-spdlog_0.4.0-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'spdlog-vendor'
ERROR: Nothing RPROVIDES 'spdlog-vendor-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/spdlog-vendor/spdlog-vendor_1.1.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'spdlog-vendor-dev'
NOTE: Runtime target 'spdlog-vendor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['spdlog-vendor-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-spdlog' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/spdlog-vendor/spdlog-vendor_1.1.1-1.bb, ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rcl-logging/rcl-logging-spdlog_0.4.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-spdlog' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-spdlog']
ERROR: Nothing RPROVIDES 'rcl-logging-spdlog-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rcl-logging/rcl-logging-spdlog_0.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rcl-logging-spdlog-dev'
NOTE: Runtime target 'rcl-logging-spdlog-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rcl-logging-spdlog-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>