{eloquent} mavlink: fix various issues
* fix typo when searching for python to fix:

DEBUG: Executing shell function do_configure
CMake Error at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/aarch64-oe-linux/mavlink/2019.12.30-1-r0/recipe-sysroot-native/usr/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:211 (message):
  No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()
Call Stack (most recent call first):
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/aarch64-oe-linux/mavlink/2019.12.30-1-r0/recipe-sysroot-native/usr/share/cmake-3.14/Modules/FindPython/Support.cmake:1170 (find_package_handle_standard_args)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/aarch64-oe-linux/mavlink/2019.12.30-1-r0/recipe-sysroot-native/usr/share/cmake-3.14/Modules/FindPython3.cmake:181 (include)
  CMakeLists.txt:27 (find_package)

-- Configuring incomplete, errors occurred!
See also "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/aarch64-oe-linux/mavlink/2019.12.30-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/aarch64-oe-linux/mavlink/2019.12.30-1-r0/temp/log.do_configure.66965)

* add python3native and python3-future-native dependency to prevent
  using host's python(2) and failing when it doesn't include future
  module:

| [21/22] cd /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/build && /usr/bin/env PYTHONPATH="/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/git:" /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/git/pymavlink/tools/mavgen.py --lang=C --wire-protocol=1.0 --output=include/v1.0 /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/git/message_definitions/v1.0/ualberta.xml
| FAILED: include/v1.0/ualberta/ualberta.h
| cd /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/build && /usr/bin/env PYTHONPATH="/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/git:" /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/git/pymavlink/tools/mavgen.py --lang=C --wire-protocol=1.0 --output=include/v1.0 /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/git/message_definitions/v1.0/ualberta.xml
| Traceback (most recent call last):
|   File "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/git/pymavlink/tools/mavgen.py", line 16, in <module>
|     from pymavlink.generator import mavgen
|   File "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/mavlink/2019.12.30-1-r0/git/pymavlink/generator/mavgen.py", line 12, in <module>
|     from future import standard_library
| ImportError: No module named future
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.

* set LICENSE manually, because superflore doesn't parse LGPLv3
  correctly and sets invalid LGPL-2 in the recipe instead

Signed-off-by: Martin Jansa <martin.jansa@lge.com>