{foxy} Add opengl to ROS_WORLD_SKIP_GROUPS
* fixes:
ERROR: Nothing PROVIDES 'mesa' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/librealsense/librealsense2_2.34.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'librealsense2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['librealsense2', 'mesa']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'librealsense2', 'mesa']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'librealsense2', 'mesa']
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'librealsense2', 'mesa']
ERROR: Nothing PROVIDES 'glfw' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/librealsense/librealsense2_2.34.0-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'librealsense2-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/librealsense/librealsense2_2.34.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'librealsense2-dev'
NOTE: Runtime target 'librealsense2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['librealsense2-dev']
ERROR: Nothing RPROVIDES 'virtual/kernel' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/librealsense/librealsense2_2.34.0-1.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'mesa' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/librealsense/librealsense2_2.34.0-1.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'glfw' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/librealsense/librealsense2_2.34.0-1.bb RDEPENDS on or otherwise requires it)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>