{eloquent} navigation2: drop dependency on nav2-rviz-plugins
* without ros-qt5 in DISTRO_FEATURES
* fixes:
ERROR: Nothing PROVIDES 'qtbase' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/navigation2/nav2-rviz-plugins_0.3.2-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-default-plugins_7.0.4-1.bb DEPENDS on or otherwise requires it). Close matches:
  netbase
NOTE: Runtime target 'nav2-rviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'navigation2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'nav2-system-tests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-system-tests', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
NOTE: Runtime target 'nav2-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nav2-bringup', 'navigation2', 'nav2-rviz-plugins', 'qtbase']
ERROR: Nothing PROVIDES 'navigation2' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/navigation2/nav2-bringup_0.3.2-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'navigation2'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>