{melodic} fcl: add dependency on octomap
* needed for moveit-core to fix:
DEBUG: Executing shell function do_compile
NOTE: VERBOSE=1 cmake --build ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/build --target all -- -j 80
...
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"moveit_core\" -Dmoveit_collision_detection_fcl_EXPORTS -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/background_processing/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/exceptions/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/backtrace/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/constraint_samplers/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/controller_manager/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/distance_field/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_distance_field/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/dynamics_solver/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/kinematics_base/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/kinematics_metrics/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/robot_model/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/transforms/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/robot_state/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/robot_trajectory/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/kinematic_constraints/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/macros/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/planning_interface/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/planning_request_adapter/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/planning_scene/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/profiler/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/sensor_manager/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/trajectory_processing/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/utils/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/devel/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot/opt/ros/melodic/include -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot/usr/include/eigen3 -Iros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot/usr/include -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0=/usr/src/debug/moveit-core/1.0.2-1-r0 -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot= -fdebug-prefix-map=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/recipe-sysroot -DNDEBUG -fPIC   -std=c++14 -Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wcast-qual -Wno-unused-parameter -Wno-unused-function -Wno-maybe-uninitialized -MD -MT collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_common.cpp.o -MF collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_common.cpp.o.d -o collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_common.cpp.o -c ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp: In function 'collision_detection::FCLGeometryConstPtr collision_detection::createCollisionGeometry(const ShapeConstPtr&, const T*, int)':
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:822:18: error: expected type-specifier
       cg_g = new fcl::OcTreed(g->octree);
                  ^~~
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:822:17: error: expected ';'
       cg_g = new fcl::OcTreed(g->octree);
                 ^~~~
                 ;
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp: In instantiation of 'collision_detection::FCLGeometryConstPtr collision_detection::createCollisionGeometry(const ShapeConstPtr&, const T*, int) [with BV = fcl::OBBRSS<double>; T = moveit::core::LinkModel; collision_detection::FCLGeometryConstPtr = std::shared_ptr<const collision_detection::FCLGeometry>; shapes::ShapeConstPtr = std::shared_ptr<const shapes::Shape>]':
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:846:96:   required from here
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:821:29: warning: unused variable 'g' [-Wunused-variable]
       const shapes::OcTree* g = static_cast<const shapes::OcTree*>(shape.get());
                             ^
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp: In instantiation of 'collision_detection::FCLGeometryConstPtr collision_detection::createCollisionGeometry(const ShapeConstPtr&, const T*, int) [with BV = fcl::OBBRSS<double>; T = moveit::core::AttachedBody; collision_detection::FCLGeometryConstPtr = std::shared_ptr<const collision_detection::FCLGeometry>; shapes::ShapeConstPtr = std::shared_ptr<const shapes::Shape>]':
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:852:97:   required from here
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:821:29: warning: unused variable 'g' [-Wunused-variable]
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp: In instantiation of 'collision_detection::FCLGeometryConstPtr collision_detection::createCollisionGeometry(const ShapeConstPtr&, const T*, int) [with BV = fcl::OBBRSS<double>; T = collision_detection::World::Object; collision_detection::FCLGeometryConstPtr = std::shared_ptr<const collision_detection::FCLGeometry>; shapes::ShapeConstPtr = std::shared_ptr<const shapes::Shape>]':
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:857:76:   required from here
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/git/collision_detection_fcl/src/collision_common.cpp:821:29: warning: unused variable 'g' [-Wunused-variable]
...
ninja: build stopped: subcommand failed.
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/temp/log.do_compile.40791)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>