{melodic} slic: fix build and installation
* it wasn't creating any package, causing do_rootfs failure:
NOTE: recipe ros-image-world-1.0-r0: task do_rootfs: Started
ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install connman packagegroup-core-boot packagegroup-ros-world run-postinsts' returned 1:
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - nothing provides slic needed by packagegroup-ros-world-melodic-1.0-r0.all
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

 * opkg_finalize_intercepts: Failed to open dir /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-OfG83e/opkg-intercept-XajUAd: No such file or directory.
 * rm_r: Failed to open dir /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-OfG83e/opkg-intercept-XajUAd: No such file or directory.
 * rm_r: Failed to open dir /jenkins/home/workspace/jansa/ros1-melodic-thud/ros1-melodic-thud/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-OfG83e: No such file or directory.

ERROR: ros-image-world-1.0-r0 do_rootfs: Function failed: do_rootfs

* that was because it wasn't installing anything at all and do_install was silently failing with:
DEBUG: Executing shell function do_install
NOTE: DESTDIR=/jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/slic/2.1.13-1-r0/image VERBOSE=1 cmake --build /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/slic/2.1.13-1-r0/build --target install -- -j 80
[0/1] cd /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/slic/2.1.13-1-r0/build && /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/slic/2.1.13-1-r0/recipe-sysroot-native/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
Error creating directory "/usr/incldue/".
gcc: error: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/slic/2.1.13-1-r0/build/slic-prefix/src/slic/slic.cpp: No such file or directory
gcc: fatal error: no input files
compilation terminated.
DEBUG: Shell function do_install finished

* because this CMakeLists.txt was very creative in a way how it build the slic
* add simple CMakeLists.txt to slic (so it can be upstreamed to
  https://github.com/garaemon/SLIC-Superpixels if anyone still
  cares)
  and adjust CMakeLists.txt to just install whatever ExternalProject
  built - this way it respects the cmake environment and can be
  cross compiled

Signed-off-by: Martin Jansa <martin.jansa@lge.com>