{eloquent} ros-distro.inc: add mapping for python3-packaging, python-virtualenv
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-packaging-native' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'ament-cmake-virtualenv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-virtualenv', 'ament-virtualenv', 'UNRESOLVED-python3-packaging-native']
NOTE: Runtime target 'ament-virtualenv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-virtualenv', 'UNRESOLVED-python3-packaging-native']
ERROR: Nothing PROVIDES 'UNRESOLVED-python-virtualenv' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-packaging' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-python-virtualenv-native' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it)

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-packaging-native' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'ament-virtualenv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-virtualenv', 'UNRESOLVED-python3-packaging-native']
NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'ament-virtualenv', 'UNRESOLVED-python3-packaging-native']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'ament-virtualenv', 'UNRESOLVED-python3-packaging-native']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'ament-virtualenv', 'UNRESOLVED-python3-packaging-native']
NOTE: Runtime target 'ament-cmake-virtualenv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-virtualenv', 'ament-virtualenv', 'UNRESOLVED-python3-packaging-native']
ERROR: Nothing PROVIDES 'python3-packaging' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it). Close matches:
  python3-can
  python-imaging
  python3-pyparsing
ERROR: Nothing PROVIDES 'UNRESOLVED-python-virtualenv-native' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'python3-virtualenv' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it). Close matches:
  python3-pretend
  python3-pytun
  python3-prctl
ERROR: Nothing PROVIDES 'ament-virtualenv' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/ament-virtualenv/ament-cmake-virtualenv_0.0.5-6.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'ament-virtualenv'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>