{crystal} remove packages which now depend on opengl DISTRO_FEATURE for default raspberrypi builds
No virtual/egl provider is available in the default setup with
vc4graphics enabled and neither opengl nor vulkan in DISTRO_FEATURES:

$ bitbake -e virtual/egl | tee env.egl
ERROR: Nothing PROVIDES 'virtual/egl'
vc-graphics-hardfp PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
vc-graphics PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics

$ bitbake -e userland 2>&1 | tee env.userland
ERROR: Nothing RPROVIDES 'libegl-mesa' (but /jenkins/mjansa/build-ros/ros2-crystal-warrior/meta-raspberrypi/recipes-graphics/userland/userland_git.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'libegl-mesa' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libegl-mesa']
ERROR: Required build target 'userland' has no buildable providers.
Missing or unbuildable dependency chain was: ['userland', 'libegl-mesa']

$ bitbake -e mesa 2>&1 | tee env.mesa
ERROR: Nothing PROVIDES 'mesa'
mesa was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES

$ bitbake -e vc-graphics-hardfp 2>&1 | tee env.vc-graphics-hardfp
ERROR: Nothing PROVIDES 'vc-graphics-hardfp'
vc-graphics-hardfp was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp

There is unbuildable dependency on virtual/egl from gstreamer1.0-plugins-base because:
1) gstreamer1.0-plugins-base depends on virtual/egl because of "egl" PACKAGECONFIG

2) "egl" PACKAGECONFIG is enabled by
   meta-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_%.bbappend
   PACKAGECONFIG_GL_rpi = "egl gles2"

   without respecting the "opengl" in DISTRO_FEATURES like the recipe in oe-core does
   openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.14.4.bb:
   PACKAGECONFIG_GL ?= "${@bb.utils.contains('DISTRO_FEATURES', 'opengl', 'gles2 egl', '', d)}"

3) virtual/egl is provided either by:
   - userland (only without vc4graphics in MACHINE_FEATURES):
     meta-raspberrypi/recipes-graphics/userland/userland_git.bb:PROVIDES += "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "", "virtual/libgles2 virtual/egl", d)}"
   - mesa (selected with vc4graphics in MACHINE_FEATURES)
     meta-raspberrypi/conf/machine/include/rpi-default-providers.inc:PREFERRED_PROVIDER_virtual/egl ?= "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "mesa", "userland", d)}"
   - vc-graphics(-hardfp)
     meta-raspberrypirecipes-graphics/vc-graphics/vc-graphics.inc:PROVIDES = "virtual/libgles2 virtual/egl"

4) vc-graphics(-hardfp) recipe are skipped in default setup, because with vc4graphics being
   in MACHINE_FEATURES by default since:
   https://github.com/agherzan/meta-raspberrypi/commit/690bdca57422447e49d4ef43862bf675e9acc28f
   the PREFERRED_PROVIDER_virtual/libgles2 is set to mesa in:
   conf/machine/include/rpi-default-providers.inc:PREFERRED_PROVIDER_virtual/libgles2 ?= "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "mesa", "userland", d)}"

   resulting in skipping the other virtual/libgles2 providers:
   vc-graphics-hardfp PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
   vc-graphics PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics

5) mesa is skipped when neither opengl nor vulkan are in DISTRO_FEATURES

6) userland doesn't provide virtual/egl because we have the default vc4graphics
   meta-raspberrypi/recipes-graphics/userland/userland_git.bb:PROVIDES += "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "", "virtual/libgles2 virtual/egl", d)}"
   and it cannot be built anyway, because with the default vc4graphics it depends on libegl-mesa:
   meta-raspberrypi/recipes-graphics/userland/userland_git.bb:RDEPENDS_${PN} += "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "libegl-mesa", "", d)}"
   and libegl-mesa is provided only by mesa recipe from oe-core which in turn
   requires either "opengl" or "vulkan" to be in DISTRO_FEATURES

This causes a lot of unresolved dependencies in default setup with vc4graphics but without opengl.
- with Yocto 2.6 Thud and older it worked, because vc4graphics wasn't enabled by default before:
  https://github.com/agherzan/meta-raspberrypi/commit/690bdca57422447e49d4ef43862bf675e9acc28f

To build these packages you have 3 options:
A) Just add "opengl" to DISTRO_FEATURES and use the default vc4graphics with mesa providing virtual/egl
B) Use DISABLE_VC4GRAPHICS added in
   https://github.com/agherzan/meta-raspberrypi/commit/96c8459c9363cc6bf463aedf4d24f92a1ee7d6ba
   to explicitly disable vc4graphics and use userland to provide virtual/egl
C) Apply https://github.com/agherzan/meta-raspberrypi/pull/551 in meta-raspberrypi,
   this part can be removed once upgrading to Yocto release with this applied

* fixes:
ERROR: Nothing PROVIDES 'virtual/egl' (but /jenkins/mjansa/build-ros/ros2-crystal-warrior/openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.14.4.bb DEPENDS on or otherwise requires it)
vc-graphics-hardfp PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
vc-graphics PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics
NOTE: Runtime target 'image-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-tools', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'packagegroup-ros-world-crystal' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-crystal', 'image-tools', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-crystal', 'image-tools', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-crystal', 'image-tools', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'image-tools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-tools-dev', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'depth-image-proc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depth-image-proc', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'depth-image-proc-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depth-image-proc-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'depthimage-to-laserscan' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depthimage-to-laserscan', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'depthimage-to-laserscan-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['depthimage-to-laserscan-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'image-geometry' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'vision-opencv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['vision-opencv', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'vision-opencv-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['vision-opencv-dev', 'image-geometry', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'image-geometry-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-geometry-dev', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'intra-process-demo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['intra-process-demo', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'intra-process-demo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['intra-process-demo-dev', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'compressed-depth-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-depth-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'image-transport-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-transport-plugins', 'compressed-depth-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'image-transport-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-transport-plugins-dev', 'compressed-depth-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'compressed-depth-image-transport-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-depth-image-transport-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'object-analytics-node' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['object-analytics-node', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'object-analytics-node-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['object-analytics-node-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'image-publisher' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-publisher', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'image-publisher-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-publisher-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'compressed-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'compressed-image-transport-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['compressed-image-transport-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'theora-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['theora-image-transport', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'theora-image-transport-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['theora-image-transport-dev', 'cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'cv-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cv-bridge', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'cv-bridge-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cv-bridge-dev', 'opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'opencv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['opencv', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'opencv-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['opencv-dev', 'gstreamer1.0-plugins-base', 'virtual/egl']
NOTE: Runtime target 'gstreamer1.0-plugins-base-meta' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-base-meta', 'virtual/egl']
NOTE: Runtime target 'gstreamer1.0-plugins-base-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-base-dev', 'virtual/egl']
NOTE: Runtime target 'gstreamer1.0-plugins-base' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-base', 'virtual/egl']
ERROR: Nothing PROVIDES 'virtual/libgles2' (but /jenkins/mjansa/build-ros/ros2-crystal-warrior/openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.14.4.bb DEPENDS on or otherwise requires it)
vc-graphics-hardfp PROVIDES virtual/libgles2 but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
vc-graphics PROVIDES virtual/libgles2 but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics

Signed-off-by: Martin Jansa <martin.jansa@lge.com>