{melodic} add new ROS_WORLD_SKIP_GROUPS element mongo and blacklist recipes depending mongo
* fixes:
ERROR: Nothing PROVIDES 'mongodb' (but generated-recipes/warehouse-ros-mongo/warehouse-ros-mongo_0.9.1-1.bb, generated-recipes/mongodb-store/mongodb-store_0.5.2-1.bb DEPENDS on or otherwise requires it)
mongodb was skipped: Recipe is blacklisted: src/mongo/util/net/ssl_manager.cpp:557:70: error: invalid conversion from 'size_t*' {aka 'unsigned int*'} to 'long unsigned int*' [-fpermissive] http://caprica.lgsvl.com:8080/Errors/Details/1509767
NOTE: Runtime target 'warehouse-ros-mongo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warehouse-ros-mongo', 'mongodb']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'warehouse-ros-mongo', 'mongodb']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'warehouse-ros-mongo', 'mongodb']
NOTE: Runtime target 'webos-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-ros-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'warehouse-ros-mongo', 'mongodb']
NOTE: Runtime target 'mongodb-store' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mongodb-store', 'mongodb']
NOTE: Runtime target 'mongodb-log' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mongodb-log', 'mongodb-store', 'mongodb']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>