{eloquent} packagegroup-ros-world-eloquent: remove cross-compile
* fixes:
  ERROR: Nothing PROVIDES 'UNRESOLVED-python3-docker' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/cross-compile/cross-compile_0.2.0-1.bb DEPENDS on or otherwise requires it)
  NOTE: Runtime target 'cross-compile' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['cross-compile', 'UNRESOLVED-python3-docker']
  NOTE: Runtime target 'packagegroup-ros-world-eloquent' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-ros-world-eloquent', 'cross-compile', 'UNRESOLVED-python3-docker']
  NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'cross-compile', 'UNRESOLVED-python3-docker']
  NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-eloquent', 'cross-compile', 'UNRESOLVED-python3-docker']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>