{foxy} rosbag2-compression: remove runtime dependency on zstd-vendor
* it's empty and not created, causing following do_rootfs error:

NOTE: ###### Generate rootfs #######
NOTE: Executing '/jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg-make-index --checksum md5 --checksum sha256 -r /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/qemux86_64/Packages -p /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/qemux86_64/Packages -m /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/qemux86_64' ...
NOTE: Executing '/jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg-make-index --checksum md5 --checksum sha256 -r /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/all/Packages -p /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/all/Packages -m /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/all' ...
NOTE: Executing '/jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg-make-index --checksum md5 --checksum sha256 -r /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/core2-64/Packages -p /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/core2-64/Packages -m /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/oe-rootfs-repo/core2-64' ...
NOTE: Installing the following packages: binutils-symlinks connman gcc-symlinks gdb ldd openssh opkg packagegroup-core-boot packagegroup-ros-world run-postinsts strace
NOTE: /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install binutils-symlinks connman gcc-symlinks gdb ldd openssh opkg packagegroup-core-boot packagegroup-ros-world run-postinsts strace
ERROR: Unable to install packages. Command '/jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install binutils-symlinks connman gcc-symlinks gdb ldd openssh opkg packagegroup-core-boot packagegroup-ros-world run-postinsts strace' returned 1:
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-ros-world-1.0-r0.qemux86_64 requires packagegroup-ros-world-foxy, but none of the providers can be installed
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world

 * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-j9pBC7/opkg-intercept-W13XV3: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-j9pBC7/opkg-intercept-W13XV3: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-j9pBC7: No such file or directory.

DEBUG: Python function do_rootfs finished

which is completely useless, because it doesn't show what's wrong with packagegroup-ros-world-foxy
to see the actual error I had to add packagegroup-ros-world-foxy directly to IMAGE_INSTALL in
ros-image-world.bb and now it shows what's wrong:

ERROR: ros-image-world-1.0-r0 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/opkg.conf -t /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp/ -o /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install binutils-symlinks connman gcc-symlinks gdb ldd openssh opkg packagegroup-core-boot packagegroup-ros-world-foxy run-postinsts strace' returned 1:
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - nothing provides zstd-vendor needed by rosbag2-compression-0.3.2-1-r0.core2-64
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-ros-world-foxy

 * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-vVGYLH/opkg-intercept-b1UD4F: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-vVGYLH/opkg-intercept-b1UD4F: No such file or directory.
 * rm_r: Failed to open dir /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/ipktemp//opkg-vVGYLH: No such file or directory.

ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/qemux86_64-oe-linux/ros-image-world/1.0-r0/temp/log.do_rootfs.35176
NOTE: recipe ros-image-world-1.0-r0: task do_rootfs: Failed

Signed-off-by: Martin Jansa <martin.jansa@lge.com>