{eloquent} plansys2-problem-expert: ignore return-type errors with webOS OSE
* fixes:
/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++  -Dplansys2_problem_expert_EXPORTS -I/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/git/include -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0=/usr/src/debug/plansys2-problem-expert/0.0.5-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0=/usr/src/debug/plansys2-problem-expert/0.0.5-1-r0                      -fdebug-prefix-map=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=i586 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/recipe-sysroot -g -fPIC   -std=gnu++17 -MD -MT CMakeFiles/plansys2_problem_expert.dir/src/plansys2_problem_expert/ProblemExpert.cpp.o -MF CMakeFiles/plansys2_problem_expert.dir/src/plansys2_problem_expert/ProblemExpert.cpp.o.d -o CMakeFiles/plansys2_problem_expert.dir/src/plansys2_problem_expert/ProblemExpert.cpp.o -c /jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/git/src/plansys2_problem_expert/ProblemExpert.cpp
/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/git/src/plansys2_problem_expert/ProblemExpert.cpp: In member function 'bool plansys2::ProblemExpert::checkPredicateTreeTypes(std::shared_ptr<plansys2::TreeNode>, std::shared_ptr<plansys2::DomainExpert>&)':
/jenkins/mjansa/build-ros/webos-eloquent-warrior/tmp-glibc/work/qemux86-webos-linux/plansys2-problem-expert/0.0.5-1-r0/git/src/plansys2_problem_expert/ProblemExpert.cpp:273:23: error: control reaches end of non-void function [-Werror=return-type]
         node->toString() << "]" << std::endl;
         ~~~~~~~~~~~~~~^~
cc1plus: some warnings being treated as errors

Signed-off-by: Martin Jansa <martin.jansa@lge.com>