{eloquent} packagegroup-ros-world-eloquent: remove popf
* Depends on coin-or libcbc for which we don't have recipes yet
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-coinor-libcbc-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/popf/popf_0.0.11-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'popf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['popf', 'UNRESOLVED-coinor-libcbc-dev']
NOTE: Runtime target 'plansys2-patrol-navigation-example' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-patrol-navigation-example', 'plansys2-executor', 'popf', 'UNRESOLVED-coinor-libcbc-dev']
NOTE: Runtime target 'plansys2-simple-example' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-simple-example', 'plansys2-executor', 'popf', 'UNRESOLVED-coinor-libcbc-dev']
NOTE: Runtime target 'plansys2-multidomain-example' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-multidomain-example', 'plansys2-executor', 'popf', 'UNRESOLVED-coinor-libcbc-dev']
NOTE: Runtime target 'plansys2-terminal' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-terminal', 'plansys2-executor', 'popf', 'UNRESOLVED-coinor-libcbc-dev']
NOTE: Runtime target 'plansys2-executor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['plansys2-executor', 'popf', 'UNRESOLVED-coinor-libcbc-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-flex' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/popf/popf_0.0.11-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-coinor-libcoinutils-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/popf/popf_0.0.11-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-bison' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/popf/popf_0.0.11-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-coinor-libclp-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/popf/popf_0.0.11-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-coinor-libcgl-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/popf/popf_0.0.11-1.bb DEPENDS on or otherwise requires it)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>