{melodic} libpcan, libfranka, rcdiscover, ypspur: ignore dev-so issues
* fixes:
ERROR: ypspur-1.17.1-1-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: ypspur path '/work/aarch64-oe-linux/ypspur/1.17.1-1-r0/packages-split/ypspur/usr/lib/libypspur-md.so'
non -dev/-dbg/nativesdk- package contains symlink .so: ypspur path '/work/aarch64-oe-linux/ypspur/1.17.1-1-r0/packages-split/ypspur/usr/lib/libformula-calc.so'
non -dev/-dbg/nativesdk- package contains symlink .so: ypspur path '/work/aarch64-oe-linux/ypspur/1.17.1-1-r0/packages-split/ypspur/usr/lib/libypspur.so'
non -dev/-dbg/nativesdk- package contains symlink .so: ypspur path '/work/aarch64-oe-linux/ypspur/1.17.1-1-r0/packages-split/ypspur/usr/lib/libcarte2d.so' [dev-so]
ERROR: ypspur-1.17.1-1-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

ERROR: rcdiscover-1.0.2-1-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: rcdiscover path '/work/aarch64-oe-linux/rcdiscover/1.0.2-1-r0/packages-split/rcdiscover/usr/lib/librcdiscover.so' [dev-so]
ERROR: rcdiscover-1.0.2-1-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

ERROR: libpcan-0.6.15-1-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: libpcan path '/work/aarch64-oe-linux/libpcan/0.6.15-1-r0/packages-split/libpcan/opt/ros/melodic/lib/libpcan.so' [dev-so]
ERROR: libpcan-0.6.15-1-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

ERROR: libfranka-0.7.1-1-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: libfranka path '/work/aarch64-oe-linux/libfranka/0.7.1-1-r0/packages-split/libfranka/usr/lib/libfranka.so' [dev-so]
ERROR: libfranka-0.7.1-1-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

* e.g. the ypspur case is interesting, we should also re-evaluate ros_faulty_solibs/ros_insane_dev_so eventually
  $ ls -lah tmp-glibc/work/aarch64-oe-linux/ypspur/1.17.1-1-r0/packages-split/ypspur/usr/lib/
  total 112K
  drwxr-xr-x 2 mjansa mjansa 4.0K Apr 23 07:03 .
  drwxr-xr-x 5 mjansa mjansa 4.0K Apr 23 07:03 ..
  lrwxrwxrwx 1 mjansa mjansa   15 Apr 23 07:03 libcarte2d.so -> libcarte2d.so.0
  lrwxrwxrwx 1 mjansa mjansa   19 Apr 23 07:03 libcarte2d.so.0 -> libcarte2d.so.0.0.0
  -rwxr-xr-x 2 mjansa mjansa 9.9K Apr 23 07:03 libcarte2d.so.0.0.0
  lrwxrwxrwx 1 mjansa mjansa   20 Apr 23 07:03 libformula-calc.so -> libformula-calc.so.0
  lrwxrwxrwx 1 mjansa mjansa   24 Apr 23 07:03 libformula-calc.so.0 -> libformula-calc.so.0.0.1
  -rwxr-xr-x 2 mjansa mjansa  20K Apr 23 07:03 libformula-calc.so.0.0.1
  -rwxr-xr-x 2 mjansa mjansa 5.7K Apr 23 07:03 libypspur-comm.so
  lrwxrwxrwx 1 mjansa mjansa   18 Apr 23 07:03 libypspur-md.so -> libypspur-md.so.14
  lrwxrwxrwx 1 mjansa mjansa   22 Apr 23 07:03 libypspur-md.so.14 -> libypspur-md.so.14.2.0
  -rwxr-xr-x 2 mjansa mjansa  27K Apr 23 07:03 libypspur-md.so.14.2.0
  lrwxrwxrwx 1 mjansa mjansa   15 Apr 23 07:03 libypspur.so -> libypspur.so.14
  lrwxrwxrwx 1 mjansa mjansa   19 Apr 23 07:03 libypspur.so.14 -> libypspur.so.14.2.0
  -rwxr-xr-x 2 mjansa mjansa  35K Apr 23 07:03 libypspur.so.14.2.0

  we need ros_faulty_solibs because of libypspur-comm.so and it's already inheritted through ros_catkin.bbclass,
  but that causes other libraries which are properly versioned to have the .so symlinks in PN, which causes the
  need for dev-so INSANE_SKIP from meta-ros-common/classes/ros_insane_dev_so.bbclass

  but that should wait after opt prefix work everywhere

Signed-off-by: Martin Jansa <martin.jansa@lge.com>